Team26SWP/InnoAlias

frontend/src/components/Lobby.tsx
=> Fixed players list appearence

frontend/src/components/Profile.tsx
=> Added deck search and filtering by tags

frontend/src/components/CreateGame.tsx, frontend/src/components/Profile.tsx, frontend/src/components/config.ts
=> Added possibility to select a saved deck for playing

frontend/src/components/Leaderboard.tsx
I mean, how could this not work?
You'll have to believe me on this one
=> Added deck export into txt with immidiate download

backend/app/models/__init__.py, backend/app/routers/game.py, backend/app/routers/profile.py, backend/tests/conftest.py, backend/tests/test_integration.py
Added a opportunity for editing the deck
**Closes #117**
=> Deck editing

frontend/src/components/CreateGame.tsx, frontend/tests/components/CreateGame.test.tsx
Added the long-awaited functionality of deleting words (also changed display to case-sensitive)
=> Added word deletion on game creation

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, README.md, pull_request_template.md
added git workflow and secrets management to the README
=> added git workflow and secrets management to the README

run_performance_test.sh
=> fixed bash script

frontend/package-lock.json, frontend/package.json
Reinstalled @types/node to update to the lates version, thus fixing ERESOLVE dependency error. Warnings about deprecated modules remain, despite using npm update, but it is not critical
=> Updated @types/node to the lates version

frontend/src/components/Profile.tsx, frontend/src/components/config.ts
Fixed bug of tags displaying more than once in the tag selection row
Fixes #147
=> Fixed tag duplication bug

frontend/src/components/Home.tsx, frontend/src/components/JoinGame.tsx, frontend/src/components/Leaderboard.tsx, frontend/src/components/Profile.tsx
Fixed bug of decks duplicating by prohibiting deck creation in this case.
Now, joining via link takes you straight to the game
Fixed #180
=> Fixed deck duplication glitch, changed link joinining a bit

frontend/src/components/Home.tsx, frontend/src/components/Leaderboard.tsx, frontend/src/components/Profile.tsx, frontend/src/components/config.ts
Added functionality to deck saving (some validity checks, privacy marker) and fixed some bugs that were already fixed
=> Added deck saving logic, re-fixed bugs resulted from git override

frontend/src/App.tsx, frontend/src/components/AiQuiz.tsx, frontend/src/components/CreateGame.tsx, frontend/src/components/Home.tsx, frontend/src/components/Profile.tsx, frontend/src/components/Quiz.tsx, frontend/src/components/config.ts
Added AI singleplayer
Closes #171 
Closes #173
=> Aigame frontend

.idea/PythonProject11.iml, .idea/inspectionProfiles/Project_Default.xml, .idea/inspectionProfiles/profiles_settings.xml, .idea/modules.xml, .idea/vcs.xml, .idea/workspace.xml, backend/app/routers/admin_panel.py
Changed admin's interaction by id's to email's
No related issues
=> Admin panel fix email

frontend/src/components/CreateGame.tsx, frontend/src/components/Home.tsx
Small fixing:
no id for non admins
Wording change in game settings
=> Small fixes frontend

backend/app/config.py, backend/app/services/aigame_service.py
Added new system prompt and context awareness
=> added new system prompt and context awareness

frontend/src/components/Home.tsx
Adding a link to the gallery via arrows to the home page
=> adding a link to the gallery via arrows to the home page

.github/workflows/ci.yml, backend/README.md, backend/app/code_gen.py, backend/app/db.py, backend/app/main.py, backend/app/models/__init__.py, backend/app/routers/admin_panel.py, backend/app/routers/aigame.py, backend/app/routers/auth.py, backend/app/routers/game.py, backend/app/routers/profile.py, backend/app/services/admin_service.py, backend/app/services/aigame_service.py, backend/app/services/auth_service.py, backend/app/services/gallery_service.py, backend/app/services/game_service.py, backend/app/services/profile_service.py, backend/tests/_test_setup.py, backend/tests/conftest.py, backend/tests/test_auth_integration.py, backend/tests/test_auth_unit.py, backend/tests/test_code_gen_unit.py, backend/tests/test_game_service_unit.py, backend/tests/test_integration.py, backend/tests/test_new_unit_tests.py, docs/API.md, docs/architecture/dynamic-view/performance-test.py, pyproject.toml
Added password validation, added deterministic game masters assignmnent when rotate_masters is true, bugfixing and refactoring
=> Bugfixing backend

backend/app/config.py, backend/app/models/__init__.py, backend/app/routers/admin_panel.py, backend/app/routers/gallery.py, backend/app/routers/profile.py, backend/app/services/admin_service.py, backend/app/services/gallery_service.py, backend/app/services/profile_service.py, backend/tests/test_admin_panel_unit.py, backend/tests/test_gallery_unit.py, backend/tests/test_integration.py, docs/API.md, docs/architecture/dynamic-view/performance-test.py
Fixed almost all bugs, small improvements in all areas
=> Bugfix backend

frontend/src/components/Lobby.tsx, frontend/src/components/Profile.tsx
- Added back to main button in lobby
- Added singleplayer support from profile page
Closes #217 
Closes #218
=> Lobby exit and singleplayer use frontend

frontend/src/components/Register.tsx
password check before sending to the backend
https://github.com/Team26SWP/InnoAlias/issues/234
=> added check boxes for the password input

frontend/src/components/Home.tsx, frontend/src/components/Register.tsx
Automatic gallery loading
https://github.com/Team26SWP/InnoAlias/issues/228
=> Automatic deck load/frontend

frontend/src/components/Home.tsx, frontend/src/components/Register.tsx
fixed use this deck bug in gallery
https://github.com/Team26SWP/InnoAlias/issues/228
=> Use deck gallery/frontend

frontend/src/components/Home.tsx, frontend/src/components/Profile.tsx
=> fixed endpoint

backend/app/services/aigame_service.py, backend/requirements.txt
fixed aigame (finally, i guess)
[provide links to issues that you addressed during your work]
=> fix aigame

frontend/src/components/Home.tsx
Added margin to the bottom, increased gallery placeholder text size, added profile check for deck usage
=> Slight gallery improvement
